/**
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
**/

#include "tb_client.h"
#include <string>
#include <memory>
#include <vector>
#include <mutex>
#include <condition_variable>
#include <asio.hpp>
#include <fmt/core.h>

namespace tb
{
  constexpr std::size_t MAX_MESSAGE_SIZE = (1024 * 1024) - 128;

  // Synchronization context between the callback and the main thread.
  struct CompletionContext
  {
    std::vector<uint8_t> reply;
    int size;
    bool completed;
    // In this example we synchronize using a condition variable:
    std::condition_variable cv;
    std::mutex mutex;
    asio::io_context::strand strand;
  };

  class Client
  {
  public:
    Client(asio::io_context &io,const std::string &host,const uint16_t port)
        : context_(io), host_(std::move(host)), port_(port) {}
    std::shared_ptr<tb_packet_t> acquire_packet(tb_packet_list_t *packet_list);
    void release_packet(tb_packet_list_t *packet_list, tb_packet_t *packet);
    void send_request(tb_client_t client, tb_packet_list_t *packets, CompletionContext *ctx);
    void on_completion(uintptr_t context, tb_client_t client, tb_packet_t *packet, const uint8_t *data, uint32_t size);

  private:
    void tb_free(void *ptr)
    {
      std::free(ptr);
    }
    std::string host_;
    uint16_t port_;
    asio::io_context &context_;
  };

  std::shared_ptr<tb_packet_t> Client::acquire_packet(tb_packet_list_t *packet_list)
  {
    // This sample is single-threaded,
    // In real use, this function should be thread-safe.
    std::shared_ptr<tb_packet_t> packet(packet_list->head);

    if (!packet)
    {
      throw std::runtime_error("Too many concurrent requests");
    }

    packet_list->head = packet->next;
    packet->next = nullptr;

    if (packet_list->head == nullptr)
    {
      packet_list->tail = nullptr;
    }

    return packet;
  }

  void Client::release_packet(tb_packet_list_t *packet_list, tb_packet_t *packet)
  {
    // This sample is single-threaded,
    // In real use, this function should be thread-safe.
    if (packet_list->head == nullptr)
    {
      packet_list->head = packet;
      packet_list->tail = packet;
    }
    else
    {
      packet_list->tail->next = packet;
      packet_list->tail = packet;
    }
  }

  void Client::send_request(tb_client_t client, tb_packet_list_t *packets, CompletionContext *ctx)
  {
    std::unique_lock<std::mutex> lock(ctx->mutex);
    ctx->completed = false;
    tb_client_submit(client, packets);
    ctx->cv.wait(lock, [&ctx]()
                 { return ctx->completed; });
  }
  void Client::on_completion(uintptr_t context, tb_client_t client, tb_packet_t *packet, const uint8_t *data, uint32_t size)
  {
    CompletionContext *ctx = static_cast<CompletionContext *>(packet->user_data);
    std::lock_guard<std::mutex> lock(ctx->mutex);
    ctx->reply.resize(size);
    std::copy(data, data + size, ctx->reply.begin());
    ctx->size = size;
    ctx->completed = true;
    ctx->cv.notify_one();
  }

  auto get_time_ms()
  {
    return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now().time_since_epoch()).count();
  }
} // namespace tb
