/*
Copyright (c) 2023 Matheus Catarino França (matheus-catarino@hotmail.com)

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
*/
#ifndef TB_CLIENT_HPP
#define TB_CLIENT_HPP
#include <array>
#include <concepts>
#include <cstdint>
#include <mutex>
#include <string>

namespace tigerbeetle {

#include <tb_client.h>

using tb_uint32_t = std::uint32_t;
using tb_uint64_t = std::uint64_t;
template <typename T>
concept tb_same =
    std::is_same_v<T, tb_uint128_t> || std::is_same_v<T, tb_transfer_t> ||
    std::is_same_v<T, tb_account_t>;

template <typename T>
concept tb_integral =
    std::is_integral_v<T> && sizeof(T) == sizeof(tb_uint128_t);

constexpr size_t MAX_MESSAGE_SIZE = (1024 * 1024) - 256;
template <std::size_t N> using accountID = std::array<tb_uint128_t, N>;
template <std::size_t N> using transferID = std::array<tb_uint128_t, N>;
template <std::size_t N> using transfer = std::array<tb_transfer_t, N>;
template <std::size_t N> using account = std::array<tb_account_t, N>;

template <std::size_t N>
concept AccountID = requires { typename accountID<N>; };
template <std::size_t N>
concept TransferID = requires { typename transferID<N>; };
template <std::size_t N>
concept TransferArray = requires { typename transfer<N>; };
template <std::size_t N>
concept AccountArray = requires { typename account<N>; };
template <std::size_t N>
  requires AccountID<N>
auto make_account() {
  return account<N>{};
}
template <std::size_t N>
  requires TransferArray<N>
auto make_transfer() {
  return transfer<N>{};
}

// Synchronization context between the callback and the main thread.
struct CompletionContext {
  std::array<uint8_t, MAX_MESSAGE_SIZE> reply;
  int size;
  bool completed;
  std::mutex mutex;
};

inline void default_on_completion([[maybe_unused]] uintptr_t context,
                                  [[maybe_unused]] tb_packet_t *packet,
                                  [[maybe_unused]] uint64_t timestamp,
                                  const uint8_t *data, uint32_t size) {
  auto ctx = static_cast<CompletionContext *>(packet->user_data);
  {
    std::lock_guard<std::mutex> lock(
        ctx->mutex); // Lock the mutex before accessing ctx members
    std::copy(data, data + size, ctx->reply.begin());
    ctx->size = size;
    ctx->completed = true;
  }
}

class Client {
public:
  explicit Client(const std::string &address,
                  std::array<uint8_t, 16> cluster_id = {},
                  uintptr_t on_completion_ctx = 0,
                  void (*on_completion_fn)(uintptr_t, tb_packet_t *, uint64_t,
                                           const uint8_t *,
                                           uint32_t) = &default_on_completion)
      : client{} {
    status =
        tb_client_init(&client, cluster_id.data(), address.c_str(),
                       address.length(), on_completion_ctx, on_completion_fn);
  }

  Client(const Client &) = delete;
  Client &operator=(const Client &) = delete;

  Client(Client &&other) noexcept : client{} {
    std::swap(client, other.client);
    std::swap(status, other.status);
  }

  Client &operator=(Client &&other) noexcept {
    if (this != &other) {
      destroy();
      std::swap(client, other.client);
      std::swap(status, other.status);
    }
    return *this;
  }

  ~Client() noexcept {
    if (client_status == TB_CLIENT_OK) {
      destroy();
    }
  }

  tb_client_t *get() { return &client; }
  const tb_client_t *get() const { return &client; }
  TB_INIT_STATUS initStatus() const { return status; }
  TB_CLIENT_STATUS clientStatus() const { return client_status; }

  void send_request(tb_packet_t &packet, CompletionContext *ctx) {
    ctx->completed = false;
    {
      std::lock_guard<std::mutex> lock(ctx->mutex);
      client_status = tb_client_submit(&client, &packet);
    }
    if (client_status == TB_CLIENT_OK) {
      while (true) {
        std::lock_guard<std::mutex> lock(ctx->mutex);
        if (ctx->completed) {
          break;
        }
      }
    }
  }

private:
  void destroy() {
    if (client.opaque[0] != 0) {
      client_status = tb_client_deinit(&client);
      std::fill_n(client.opaque, 4, 0);
    }
  }

  tb_client_t client;
  TB_INIT_STATUS status;
  TB_CLIENT_STATUS client_status;
};
} // namespace tigerbeetle
#endif // TB_CLIENT_HPP