/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
*/

#pragma once
#include <array>
#include <fmt/core.h>
#include <fmt/color.h>
#include <memory>

namespace tigerbeetle {
#include <tb_client.h>

constexpr size_t MAX_MESSAGE_SIZE = (1024 * 1024) - 128;
template <std::size_t N> using accountID = std::array<tb_uint128_t, N>;
template <std::size_t N> using transferID = std::array<tb_uint128_t, N>;
template <std::size_t N> using transfer = std::array<tb_transfer_t, N>;
template <std::size_t N> using account = std::array<tb_account_t, N>;
template <std::size_t N> auto make_account() { return account<N>{}; }
template <std::size_t N> auto make_transfer() { return transfer<N>{}; }
// Synchronization context between the callback and the main thread.
struct CompletionContext {
  std::array<uint8_t, MAX_MESSAGE_SIZE> reply;
  int size;
  bool completed;
};

inline void on_completion([[maybe_unused]] uintptr_t context,
                          [[maybe_unused]] tb_client_t client,
                          tb_packet_t *packet, const uint8_t *data,
                          uint32_t size) {
  auto ctx = static_cast<CompletionContext *>(packet->user_data);
  std::copy(data, data + size, ctx->reply.begin());
  ctx->size = size;
  ctx->completed = true;
}

inline void send_request(tb_client_t client, tb_packet_t *packet,
                         CompletionContext *ctx) {
  // Submits the request asynchronously:
  ctx->completed = false;
  tb_client_submit(client, packet);
  while (!ctx->completed) {
    // Wait for completion
  }
}

enum class LogLevel {
  INFO,
  DEBUG,
  ERROR,
  WARN,
  TRACE,
};

class Logger {
public:
  static void warn(const std::string &message){
    println(LogLevel::WARN, message);
  }
  static void trace(const std::string &message){
     println(LogLevel::TRACE, message);
  }
  static void debug(const std::string &message){
     println(LogLevel::DEBUG, message);
  }
  static void info(const std::string &message){
     println(LogLevel::INFO, message);
  }
  static void error(const std::string &message){
    println(LogLevel::ERROR, message);
  }
private:
  static fmt::color getLogLevelColor(LogLevel level) {
    switch (level) {
    case LogLevel::INFO:
      return fmt::color::green;
    case LogLevel::DEBUG:
      return fmt::color::cyan;
    case LogLevel::ERROR:
      return fmt::color::red;
    case LogLevel::WARN:
      return fmt::color::yellow;
    case LogLevel::TRACE:
      return fmt::color::white;
    }
    return static_cast<fmt::color>(
        0x000000); // Default color if the level is unknown
  }

  static void println(LogLevel level, const std::string &message) {
    fmt::color color = getLogLevelColor(level);
    fmt::print(fg(color), "[{}] {}\n", getLogLevelString(level), message);
  }

  static std::string getLogLevelString(LogLevel level) {
    switch (level) {
    case LogLevel::INFO:
      return "info";
    case LogLevel::DEBUG:
      return "debug";
    case LogLevel::ERROR:
      return "error";
    case LogLevel::WARN:
      return "warn";
    case LogLevel::TRACE:
      return "trace";
    }
    return "unknown"; // Default log level if unknown
  }
};

} // namespace tigerbeetle