name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: '13 8 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04-arm, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest

      - name: CMake - Configure
        run: cmake -B build -DUSE_FMT=ON -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release

      - name: CMake - Build C++ client
        run: |
            cmake --build build --parallel && \
            cmake --build build --target testing

  msys2-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - { sys: mingw64, env: x86_64 } # msvcrt + libstdc++
        - { sys: ucrt64,  env: ucrt-x86_64 } # ucrt + libstdc++
        - { sys: clang64, env: clang-x86_64 } # ucrt + libc++
    steps:
      - uses: actions/checkout@v4
        with:
          path: temp
          submodules: recursive
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          path-type: inherit
          location: D:\
          install: git mingw-w64-${{matrix.env}}-cmake mingw-w64-${{matrix.env}}-toolchain
          update: true
      
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CMake - Configure
        shell: msys2 {0}
        run: |
            cd /C/_
            cmake -B build -DUSE_FMT=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
      
      - name: CMake - Build C++ client
        shell: msys2 {0}
        run: |
            cd /C/_
            cmake --build build --parallel && cmake --build build --target testing


  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
